# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sip_server.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sip_server.Request" do
    optional :from, :string, 1
    optional :to, :string, 2
    optional :body, :string, 3
  end
  add_message "sip_server.Response" do
    optional :status, :string, 1
    optional :reason, :string, 2
  end
end

module SipServer
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("sip_server.Request").msgclass
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("sip_server.Response").msgclass
end
