# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sip_server.proto for package 'sip_server'

require 'grpc'
require 'sip_server_pb'

module SipServer
  module Action
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sip_server.Action'

      rpc :sendMessage, Request, Response
    end

    Stub = Service.rpc_stub_class
  end
end
